# Generated by Django 6.0 on 2026-08-02 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_favori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='panieritem',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panier_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panieritem',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
