# Generated by Django 6.0 on 2026-08-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_panieritem_utilisateur_alter_panieritem_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('wave', 'Wave'), ('orange', 'Orange Money'), ('especes', 'Paiement à la livraison')], max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='pays',
            field=models.CharField(default="Cote d'ivoire", max_length=100),
        ),
    ]
