# Generated by Django 6.0 on 2026-08-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_alter_commande_mode_paiement_alter_commande_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='pays',
            field=models.CharField(default="Côte d'Ivoire", max_length=100),
        ),
    ]
