# Generated by Django 6.0 on 2026-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_alter_commande_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
